on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: gmdemo.azurecr.io
        username: ${{ secrets.acr_gmdemo_username }}
        password: ${{ secrets.acr_gmdemo_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/amd64/hello-world" -f  "amd64/hello-world/Dockerfile" -t gmdemo.azurecr.io/gmdemo:${{ github.sha }}
        docker push gmdemo.azurecr.io/gmdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_gmdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep gm-demo9e8b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace gm-demo9e8b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: gm-demo9e8b
        container-registry-url: gmdemo.azurecr.io
        container-registry-username: ${{ secrets.acr_gmdemo_username }}
        container-registry-password: ${{ secrets.acr_gmdemo_password }}
        secret-name: gmdemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: gm-demo9e8b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          gmdemo.azurecr.io/gmdemo:${{ github.sha }}
        imagepullsecrets: |
          gmdemodockerauth